
all:	dasm88 zasm88 analyze88 knj2font88


dasm88:		dasm88.c
	cc -o dasm88 dasm88.c

zasm88:		zasm88.c
	cc -o zasm88 zasm88.c

analyze88:	analyze88.c
	cc -o analyze88 analyze88.c

knj2font88:	knj2font88.c
	cc -o knj2font88 knj2font88.c


clean:
	rm -f dasm88 zasm88 analyze88 knj2font88
